const v2Domain = 'https://v2.keegandonley.com';

module.exports = [
  // origin | destination | permanent
  ['/twitter', 'https://twitter.com/keegandonley'],
  ['/linkedin', 'https://www.linkedin.com/in/k10y/'],
  ['/github', 'https://github.com/keegandonley'],
  ['/instagram', 'https://www.instagram.com/keegandonley'],
  ['/dribbble', 'https://dribbble.com/keegandonley'],
  ['/dribble', 'https://dribbble.com/keegandonley'],
  ['/peloton', 'https://members.onepeloton.com/members/keegancodes/overview'],
  ['/instagram', 'https://www.instagram.com/keegandonley/'],
  ['/polywork', 'https://www.polywork.com/keegandonley'],
  ['/atl', '/render24'],
  ['/renderatl', '/atl'],
  ['/render', '/atl'],
  ['/tailwind', '/hi/tailwind'],
  ['/tailwindconnect', '/hi/tailwind'],
  ['/timeoutJS', 'https://keegandonley.github.io/timeoutJS/'],
  ['/subscribe', 'https://keegancodes.beehiiv.com/subscribe'],
  [
    '/refer/render',
    'https://ti.to/render-atlanta/2023/discount/2023Ref-keegan@kizen.com',
  ],
  ['/vinyl', `${v2Domain}/vinyl`],
  ['/vinyl/:slug*', `${v2Domain}/vinyl/:slug*`],
  ['/contact', '/hi'],
  ['/shortcuts', `${v2Domain}/shortcuts`],
  ['/qr/:slug*', `${v2Domain}/qr/:slug*`],
  ['/bsky', 'https://bsky.app/profile/keegan.codes'],
  ['/bluesky', '/bsky'],
  ['/render23recap', '/slides/render23'],
  ['/v2', v2Domain],
  ['/girlstart', 'https://give.girlstart.org/team/542895'],
  ['/reddit', 'https://www.reddit.com/user/keegancodes'],
  ['/strava', 'https://www.strava.com/athletes/17351940'],
  ['/consulting', 'https://fantastical.app/keegancodes/consultation'],
  ['/paid-consultation', 'https://fantastical.app/keegancodes/consultation'],
  ['/1-1', 'https://fantastical.app/keegancodes/1-1-chat'],
  [
    '/zwift',
    'https://www.zwift.com/athlete/ba93b27d-b57e-4aeb-9384-54c5870a3a57',
  ],
];
